### PR TITLE
Add Travis check for exercises

### PR DESCRIPTION
**Pull request by budmc29**
Fixes: #148 

OSX was adde as a target system, but I had to wait 10 minutes and a build was not started, it's probably not worth the wait since probably resources for OS are scarce.

I need to wait until all the other PR are merged before merging this one, and then fixing the commits and squashing.

### CODE REVIEW

**Comment by kotp** [comment]
Are the exercise files that are here part of the testing travis-ci feature?  Should they be excluded from this PR?  Or as things come in, will they "catch up" so that the change will only include the Travis related setup?

**Comment by budmc29** [comment]
The exercise changes are not needed for the PR, I added them only to make sure I have the script working properly without waiting for the opened PR for them to merged.

I have to admit that I don't know how to do it properly, would `git rebase` help with this?
 Probably I'll create another branch and use cherry-pick, but I'm open to better suggestions.

**Comment by sjwarner-bp** [comment]
I think either:
* creating a new branch and cherry-picking commits across would work
* reverting previous unneeded commits and then squashing them
* rebasing

Whichever is easiest for you, go ahead and do! Then I'll give it a thorough look over :slightly_smiling_face:

**Comment by budmc29** [comment]
Commits fixed.

**Comment by budmc29** [comment]
Thanks.

**Pull request merged**
