### PR TITLE
Error handling exersise #47

### PR DESCRIPTION
**Pull request by jaggededgedjustice**
Currently only has argument checking

### CODE REVIEW

**Comment by kotp** [comment]
So far so good.

**Comment by jaggededgedjustice** [comment]
Reworked so the script can be sourced to check that `set -eu` has been used

**Comment by kytrinyx** [comment]
Thanks @jaggededgedjustice! If you add the exercise to the `config.json` file's "exercises" array, we should be able to merge the pull request.

**Comment by kytrinyx** [comment]
@jaggededgedjustice Thanks! Would you rebase against the most recent upstream master? We've added some new keys that you'll need to add (if you get stuck I can go ahead and do this for you, but I wanted to give you a chance to do it if you have time).

**Comment by kytrinyx** [comment]
This looks great, @jaggededgedjustice. Once the build passes I'll get this merged. 🌷 Thank you

**Pull request merged**
