### PR TITLE
port: variable-length-quantity

### PR DESCRIPTION
**Pull request by glennj**
exercise [README.md](https://github.com/glennj/bash/blob/port/variable-length-quantity/exercises/variable-length-quantity/README.md)  
problem spec [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/variable-length-quantity/canonical-data.json)

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by glennj** [comment]
Now, why is the build still showing as pending? The details make it seem like it finished.

**Comment by guygastineau** [comment]
I was wondering that myself 3 1/2 hours ago, but I figured it would have resolved itself by now.

Travis seems to know it is finished.  What is going on with GitHub?

**Comment by guygastineau** [comment]
@iHiD this is the one.

**Comment by iHiD** [comment]
Restarted

**Comment by guygastineau** [comment]
Thank you so much @iHiD

**Comment by glennj** [comment]
Is there a way to trigger a build without pushing a commit?

**Comment by guygastineau** [comment]
I just figured out how to do it.

I had to register my GitHub account with Travis, and now I can trigger rebuilding for repos where I have write access.

**Pull request merged**
