### PR TITLE
Add Bash maintainer entry for bkhl

### PR DESCRIPTION
**Pull request by bkhl**
Bash maintainer entry for myself.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by guygastineau** [comment]
Nice bio.

I think in our scenario you are already demonstrably committed and qualified enough to include `true` for showing on the website.  That is only if you want to.  No pressure.

**Comment by bkhl** [comment]
@iHiD asked in his comment in the #v3 slack channel that we leave it as `false` for now. I understand they will flip them for all the new maintainers at once at some point soon.

**Comment by guygastineau** [comment]
Indeed.  That was what I meant to reference.  Essential, a lot of the new recruits are truly new.  You have been active in some capacity for a decent amount of time here.  It is very appreciated ;)

Anyway, I don't think it is a big deal, but I wanted you to know that your are welcome to have it show already on the website if you want.

**Comment by iHiD** [comment]
> Anyway, I don't think it is a big deal, but I wanted you to know that your are welcome to have it show already on the website if you want.

Yes. You have clearly "earned" the right to have `true`

**Pull request merged**
