### PR TITLE
Bats fix arrays in tests

### PR DESCRIPTION
**Pull request by glennj**
The `bats` that gets installed as a package on ubuntu alters IFS while the tests are running. This breaks the tests for `series` and `sieve`.

It seems the simplest solution is to stop using arrays in the tests.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by glennj** [comment]
I'm surprised this didn't break on CI. I'm using bats-core on my mac: I ended up installing a ubuntu VM to reproduce.

**Comment by kotp** [comment]
Thanks for the work on this.

**Comment by guygastineau** [comment]
Sweet.  Did this fix #382 ?

**Comment by glennj** [comment]
Yes it did.

**Pull request merged**
