### PR TITLE
bantor: add logging

### PR DESCRIPTION
**Pull request by glennj**
Added logging: it's not specific log messages, but (most) of the session is dumped into the log file.

I also moved some functions around which contributes to the bulk of the diff.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by guygastineau** [comment]
Nice

**Comment by kotp** [comment]
Was looking forward to seeing the two commits... unfortunate that it was only one.

**Comment by glennj** [comment]
What else are you hoping for @kotp ?

**Comment by kotp** [comment]
Looked like there should have been two commits... one for the logging, another for the rearrangement.

**Pull request merged**
