### PR TITLE
Add language attribute to config.json

### PR DESCRIPTION
**Pull request by thirdppp**
language

### CODE REVIEW

**Comment by Smarticles101** [comment]
Thanks for the fix @thirdppp, and happy first-time contribution :) just remember next time to have a more descriptive title, commit message, and pull request description.

**Comment by thirdppp** [comment]
thanks for your comment. i will try hard for your project

**Comment by Insti** [comment]
@Smarticles101 this commit has undone a change applied by kytrinyx to normalize the config files.

See: https://github.com/exercism/bash/commit/a456d378a52b7fe23b3117e1fd4045f95756d990

**Comment by Smarticles101** [comment]
@Insti thanks, I didn't catch that.

**Pull request merged**
