### PR TITLE
Move error-handling in config.json in order to keep exercises in difficulty order.

### PR DESCRIPTION
**Pull request by sjwarner-bp**
Add Triangle exercise to bash language stream.

Additionally, moved `error-handling` in `config.json` in order to keep exercises in difficulty order.

### CODE REVIEW

**Comment by Smarticles101** [comment]
Thanks @sjwarner-bp however, a pull request to add the triangle exercise had already been made before this one (Ref #95). However, the placement of `error-handling` in config.json was a good catch as I don't think that was intentionally placed at the end. If you would like to repurpose this pull request for that change, feel free

**Comment by Smarticles101** [comment]
@sjwarner-bp Just checking in, do you plan on addressing my previous comment? If not, let me know and I can keep your valid changes and merge those :)

**Comment by Smarticles101** [comment]
You can do that or you can revert the two first commit's and just commit moving `error-handling` in config.json. If you do the former, I will likely squash and merge to get rid of the extra commits

**Comment by sjwarner-bp** [comment]
All done now - I think this is ok? Please let me know, and sorry for the wait!

**Comment by Smarticles101** [comment]
So far so good @sjwarner-bp I just need you to remove `triangle` exercise from config.json :)

**Comment by sjwarner-bp** [comment]
Oops, of course! Sorry - too much context switching :laughing:

**Comment by Smarticles101** [comment]
@sjwarner-bp of course, I understand and it's totally okay :) thanks for the changes

**Comment by Smarticles101** [comment]
Sorry your work on `triangle` couldn't be merged, feel free to look at other unimplemented ones and implement one of them if you'd like :)

**Comment by sjwarner-bp** [comment]
Thanks for helping me out @Smarticles101

**Pull request merged**
