### PR TITLE
Updated roman-numerals difficulty

### PR DESCRIPTION
**Pull request by edwin0258**
More accurate difficulty for roman-numerals.

### CODE REVIEW

**Comment by budmc29** [comment]
I'll give the exercise a try and see how difficult it is in bash.

**Comment by edwin0258** [comment]
roman-numerals was about as difficult as gigasecond or luhn for me. Definitely not the hardest problem of the available ones.

**Comment by budmc29** [comment]
@kotp what do you think?

**Comment by kotp** [comment]
I will say go with the 4.  The difficulty can definitely be subjective, due to the students own restrictions.  It is bash, and as such, is it a strictly "bash" solution, what limitations do you put on yourself for solving the problems.

The (strictly) bash solution does not appear to be too difficult though, relatively speaking.

**Comment by budmc29** [comment]
Thank you @edwin0258

**Pull request merged**
