### PR TITLE
Configlet run to update exercises

### PR DESCRIPTION
**Pull request by kotp**
`bin/configlet generate .` run.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by guygastineau** [comment]
So this doesn't get us any closer to understanding why `bin/fetch-configlet` failed in #328 does it?

**Comment by kotp** [comment]
I believe so, I gave the argument `.` for `bin/configlet` which directs it to the `config.json` file.

**Comment by guygastineau** [comment]
Right, but the CO failure is happening before configlet is even fetched from the `exercism/configlet` repo.

**Comment by guygastineau** [comment]
```
$ bin/fetch_configlet
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command "bin/fetch_configlet" failed and exited with 2 during .
```

**Comment by guygastineau** [comment]
Thank you.

**Pull request merged**
