### PR TITLE
stub: should be executable

### PR DESCRIPTION
**Pull request by guygastineau**
I realized once I copied the  stub to all exercises, that they weren't executable.  I think we fixed our tests, so that none of them require an executable script, but that might not be the case.

I remember a lot of frustration the first time I came across a test requiring an executable solution script. BATS doesn't give a good error message for this.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by guygastineau** [comment]
@kotp It won't show any changes here, but it does say it is executable now.

I just wanted someone else to see it before this trivial change is merged :smile:

**Comment by guygastineau** [comment]
@glennj @IsaacG 

A simple confirmation from either of you would also suffice.

**Comment by guygastineau** [comment]
Thank you.

**Comment by kotp** [comment]
> @kotp It won't show any changes here, but it does say it is executable now.

Not true, it shows:

`100644 → 100755` as expected.

**Comment by guygastineau** [comment]
Ah, I see.

**Pull request merged**
