### PR TITLE
port: beer-song

### PR DESCRIPTION
**Pull request by glennj**
This is the last one I have queued up for now.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by guygastineau** [comment]
Really great work!

I would prefer if the error tests at the bottom expected a non zero retval.

Also, you can enforce expected error messages for them even if they are not included in the problem specifications repo.

**Comment by glennj** [comment]
The errors *do* expect a non-zero status, the operator is `-ne`.

**Comment by guygastineau** [comment]
Thanks, you are right.  I guess my eyes glossed over the `-ne`.  That'll teach me to do this from a phone :laughing: 

I'll look at your latest changes and request the eyes of another maintainer before merging.

**Comment by guygastineau** [comment]
Thank you @kotp 

Thank you @glennj

**Pull request merged**
