### PR TITLE
Apply styleguide to isogram

### PR DESCRIPTION
**Pull request by budmc29**

### CODE REVIEW

**Comment by guygastineau** [comment]
I assume this is ready to be merged?

**Comment by guygastineau** [comment]
Thank you

**Comment by budmc29** [comment]
Shellcheck does complain of doing `'` anytime, so it's a bit unfortunate.
From working with it so far, we'll use it as a starting suggestion, and having to ignore some changes, since the project is not as flexible or mature as something like `rubocop` or `eslint`.

**Comment by guygastineau** [comment]
That sounds reasonable.

**Pull request merged**
