### PR TITLE
port: markdown

### PR DESCRIPTION
**Pull request by glennj**
exercise [README.md](https://github.com/glennj/bash/blob/port/markdown/exercises/markdown/README.md)  
problem spec [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/markdown/canonical-data.json)

Note that the problem specification [wants this to be a *refactoring* exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/markdown/description.md). I did not have it in me to write a crappy yet working markdown parser.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by guygastineau** [comment]
Nice work.

Thank you for pointing out that your example won't correctly nest `<strong>` inside `<em>`.

At some point someone should PR to prob-spec some nesting tests so the behavior will be defined in the implementations. Until that happens though your example is fine.

**Comment by guygastineau** [comment]
Does everyone think we should make this a refactoring exercise?

We could just take your example and keep it functioning while making it much worse?

I don't mind taking a stab at ruining the readability and performance of your example script 😂

**Comment by IsaacG** [comment]
We don't have any refactoring exercises and refactoring is a whole different skillset/problem.
On the one hand, we can remain consistent. On the other, it might be nice to expand the skills used.

**Comment by glennj** [comment]
Some thoughts about how to unfactor, aka crapify:
* no functions (one giant state machine?)
* lots and lots of code duplication
* lots of variables
* stick to good coding practices: quoting, reading from the file.
* maybe use sh constructs, `[` not `[[`, don't use `+=` assignment
    * or maybe sprinkle one or two bash syntax elements in to encourage users to discover them.
* can we avoid regex? A good markdown parser probably won't use regex anyway.
* probably want to get inspiration from python code (ruby track has not implemented this one)

**Comment by glennj** [comment]
I'm going to withdraw this PR and have another crack at it.

A question: what are the mechanics of putting it into git so that when the user downloads the exercise, there is a "markdown.sh" file waiting for them? Can the repo  have a "markdown.sh"? It will get trashed during testing.

**Comment by kotp** [comment]
What ever you put in the folder will be delivered to the student... With an exception of, I think, `.meta` as a folder... I would have to check.  But yes, as far as I can remember, you can deliver whatever file you want to in the exercise by placing it there.

**Comment by guygastineau** [comment]
@glennj so to be clear:

You are going to try your hand at making a sloppy-but-passing solution to be refactored in addition to the better example.sh?

**Comment by glennj** [comment]
That's right.

**Pull request closed without merging**
