### PR TITLE
Updated roman-numerals

### PR DESCRIPTION
**Pull request by guygastineau**
---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

### CODE REVIEW

**Comment by guygastineau** [comment]
[canonical-data.json](https://github.com/guygastineau/problem-specifications/blob/master/exercises/roman-numerals/canonical-data.json)

**Comment by budmc29** [comment]
Thank you.

**Comment by budmc29** [comment]
Correct problem-specification link: https://github.com/exercism/problem-specifications/blob/master/exercises/roman-numerals/canonical-data.json

**Comment by guygastineau** [comment]
Thanks for correcting that link.  I didn't see I was in my own fork. Haha

**Pull request merged**
