### PR TITLE
luhn: add to track

### PR DESCRIPTION
**Pull request by sjwarner-bp**
As part of fleshing out the track, I've added `luhn`.

I need to fix the conflict, but once someone has approved it then I'll fix that in the web-editor and merge in 🙂

### CODE REVIEW

**Comment by budmc29** [comment]
Looks good, can you uncomment all the tests except the first one?

**Comment by sjwarner-bp** [comment]
Oops, silly mistake from testing! On it now 👍 

Thanks for the reviews 🙂

**Comment by sjwarner-bp** [comment]
Should be fixed - once it's approved I'll fix the conflict and then merge 🙂

**Comment by budmc29** [comment]
The problem-specification for this exercise asks that the expected output is either true or false, what do you say about replacing the exit status with an explicit return or print in the tests?

Bash exit code of 0 means true, but other languages treat 0 as false and 1 as true, and this might cause confusion, and at the same time allows users to use the script from the CLI and see an output which makes the default use case for bash scripts.

I have nothing against integrating the exercise as it is, but it might be worth discussing about this since looking at the other exercises all of them except `armstrong_numbers` and `triangle` are following this convention.

**Comment by sjwarner-bp** [comment]
That makes sense to me - I can get working on it, and once that's done correct the other two!

It would be a good idea for us to document this somewhere (alongside justification) 🙂

**Comment by budmc29** [comment]
Added info with https://github.com/exercism/bash/pull/123.

**Comment by sjwarner-bp** [comment]
Think this should do it - let me know what you think @budmc29 🙂

**Comment by budmc29** [comment]
Maybe is better to output to the terminal `true` just like the specification, it will help avoiding the confusion for 0 being true or false.

**Comment by sjwarner-bp** [comment]
Like this? 🙂

**Comment by budmc29** [comment]
Awesome, that look very good. Thank you.

**Comment by budmc29** [comment]
I'm ready to merge it if you resolve the conflict.

**Comment by sjwarner-bp** [comment]
Perfect, I'll resolve the conflict when I'm back at my laptop! 🙂

**Pull request merged**
